---
namespace: ivansible
name: cert
version: 1.0.0

description: Ansible collection for CertBot

authors:
  - Ivan Andreev <ivandeex@gmail.com>

tags:
  - certbot
  - letsencrypt
  - cloudflare
  - linux

# https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification
# namespace.name: version_range
dependencies: {}

repository: https://github.com/ivansible/cert
documentation: https://github.com/ivansible/cert
homepage: https://github.com/ivansible/cert
issues: https://github.com/ivansible/cert/issues

readme: README.md
license: MIT

build_ignore:
  - '*.pyc'
  - '*.tar'
...
