---
# flush_handlers is an included task to avoid the below warning:
# "flush_handlers task does not support when conditional"
- name: flush postponed handlers now
  ansible.builtin.meta: flush_handlers
...
