---
- name: use import to become root globally
  ansible.builtin.import_tasks: root.yml
  become: true
  tags:
    - cert_replica_all

- name: run postponed handlers now
  ansible.builtin.include_tasks: flush-handlers.yml
  tags:
    - cert_replica_all
...
