---
- name: install certbot
  ansible.builtin.import_role:
    name: ivansible.base.cert
    tasks_from: install.yml
  vars:
    certbot_stop_timer: true
  tags: cert_replica_install

- name: install rsync package
  ansible.builtin.apt:
    name: rsync
    state: present
    install_recommends: false
  notify:
    - run receive handler once to fix file/directory permissions
  tags: cert_replica_install


- name: configure sudoers
  ansible.builtin.import_tasks: sudo.yml
  tags: cert_replica_sudo

- name: authorize ssh keys with pull user
  ansible.builtin.import_tasks: keys.yml
  tags: cert_replica_ssh


- name: create post-receive handler script
  ansible.builtin.template:
    src: certbot-post-receive.sh
    dest: "{{ certbot_replica_handler }}"
    mode: 0700
  tags: cert_replica_receive
...
