---
- name: allocate transient certbot archive on master
  ansible.builtin.tempfile:
    state: file
    prefix: ansible.letsencrypt.certs.
    suffix: .tar.gz
  delegate_to: "{{ certbot_master_host }}"
  register: _cert_master_archive
  notify: remove temporary certbot archive on master

- name: allocate transient certbot archive on controller
  ansible.builtin.tempfile:
    state: file
    prefix: ansible.certbot-certs.
    suffix: .tar.gz
  connection: local
  register: _cert_controller_archive
  notify: remove temporary certbot archive on controller

- name: fill temporary certbot archive on master with certificates
  community.general.archive:
    path:
      - "{{ certbot_live_dir }}"
      - "{{ certbot_arch_dir }}"
    dest: "{{ _cert_master_archive.path }}"
    mode: 0644
  delegate_to: "{{ certbot_master_host }}"
  become: true

- name: download archived certificates from master to controller
  ansible.builtin.fetch:
    src: "{{ _cert_master_archive.path }}"
    dest: "{{ _cert_controller_archive.path }}"
    flat: true
  delegate_to: "{{ certbot_master_host }}"
...
